### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by vbelus** [vbelus/falling-liquid-film-drl#1]
@jerabaul29

**Comment by jerabaul29** [comment]
Perfect, I will go through it on Monday :)

**Comment by jerabaul29** [comment]
Looks good, please close.

**Comment by jerabaul29** [comment]
@vbelus your old file about how to run:

"
- For Ubuntu/Mac users :
To launch the docker, go into the folder where this README file is with a bash shell :
$ cd [path]

Then load the docker image :
$ sudo docker load -i tp_fluid_film.tar

And run it :
$ docker run -it -p 8888:8888 tp_fluid_film:latest

It will then ask you to paste a certain adress in your browser, do that

- For windows users :

To launch the docker, go into the folder where this README file is with a PowerShell (open a PowerShell by typing PowerShell in the search bar) :
$ cd [path]

Then load the docker image :
$ docker load -i tp_fluid_film.tar

And run it :
$ docker run -it -p 8888:8888 tp_fluid_film:latest

It will then ask you to paste a certain adress in your browser, it should look like this :
http://0.0.0.0:8888/?token=blablabla

Just replace 0.0.0.0 by localhost, that is, copy/paste this exact adress in your browser by replacing 0.0.0.0 by localhost :
http://localhost:8888/?token=blablabla

"
